# Generated by Django 4.1 on 2022-09-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
