# Generated by Django 4.1 on 2022-09-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_hotel_size_hotel_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='size',
            new_name='capacity',
        ),
    ]
